[package]
edition = "2021"
name = "access-atmosphere"
version = "0.3.0-alpha.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
name = "access_atmosphere"

[dependencies]
ndarray = "0.15.4"
num-complex = "0.4.2"
numpy = "0.16.2"
once_cell = "1.13.0"
pyo3 = {version = "0.16.5", features = ["extension-module"]}
rayon = "1.5.3"
smallvec = "1.9.0"

[features]
abi3 = ["pyo3/abi3-py38", "generate-import-lib"]
generate-import-lib = ["pyo3/generate-import-lib"]

[package.metadata.maturin]
python-source = "python"

[profile.dev]
opt-level = 1
